all:
  vars:
    ansible_port: 22251
    ansible_ssh_private_key_file: arix
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  children:
    routeservers:
      hosts:
        rs1:
          ansible_host: rs1.arix.dev
          ipv4: 44.190.42.253
          ipv6: 2602:801:30ff::253
        rs2:
          ansible_host: rs2.arix.dev
          ipv4: 44.190.42.254
          ipv6: 2602:801:30ff::254
